// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MathPerso.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MathPerso {
  public static partial class MathPerso
  {
    static readonly string __ServiceName = "MathPerso.MathPerso";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MathPerso.Nombre> __Marshaller_MathPerso_Nombre = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MathPerso.Nombre.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MathPerso.Resultat> __Marshaller_MathPerso_Resultat = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MathPerso.Resultat.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MathPerso.Nombre, global::MathPerso.Resultat> __Method_Factorielle = new grpc::Method<global::MathPerso.Nombre, global::MathPerso.Resultat>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Factorielle",
        __Marshaller_MathPerso_Nombre,
        __Marshaller_MathPerso_Resultat);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MathPerso.Nombre, global::MathPerso.Resultat> __Method_Addiction = new grpc::Method<global::MathPerso.Nombre, global::MathPerso.Resultat>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Addiction",
        __Marshaller_MathPerso_Nombre,
        __Marshaller_MathPerso_Resultat);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MathPerso.Nombre, global::MathPerso.Resultat> __Method_Calcul = new grpc::Method<global::MathPerso.Nombre, global::MathPerso.Resultat>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Calcul",
        __Marshaller_MathPerso_Nombre,
        __Marshaller_MathPerso_Resultat);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MathPerso.MathPersoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MathPerso</summary>
    [grpc::BindServiceMethod(typeof(MathPerso), "BindService")]
    public abstract partial class MathPersoBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Factorielle(global::MathPerso.Nombre request, grpc::IServerStreamWriter<global::MathPerso.Resultat> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::MathPerso.Resultat> Addiction(grpc::IAsyncStreamReader<global::MathPerso.Nombre> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Calcul(grpc::IAsyncStreamReader<global::MathPerso.Nombre> requestStream, grpc::IServerStreamWriter<global::MathPerso.Resultat> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MathPerso</summary>
    public partial class MathPersoClient : grpc::ClientBase<MathPersoClient>
    {
      /// <summary>Creates a new client for MathPerso</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MathPersoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MathPerso that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MathPersoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MathPersoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MathPersoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::MathPerso.Resultat> Factorielle(global::MathPerso.Nombre request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Factorielle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::MathPerso.Resultat> Factorielle(global::MathPerso.Nombre request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Factorielle, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MathPerso.Nombre, global::MathPerso.Resultat> Addiction(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Addiction(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MathPerso.Nombre, global::MathPerso.Resultat> Addiction(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Addiction, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::MathPerso.Nombre, global::MathPerso.Resultat> Calcul(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Calcul(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::MathPerso.Nombre, global::MathPerso.Resultat> Calcul(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Calcul, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MathPersoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MathPersoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MathPersoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Factorielle, serviceImpl.Factorielle)
          .AddMethod(__Method_Addiction, serviceImpl.Addiction)
          .AddMethod(__Method_Calcul, serviceImpl.Calcul).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MathPersoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Factorielle, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::MathPerso.Nombre, global::MathPerso.Resultat>(serviceImpl.Factorielle));
      serviceBinder.AddMethod(__Method_Addiction, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::MathPerso.Nombre, global::MathPerso.Resultat>(serviceImpl.Addiction));
      serviceBinder.AddMethod(__Method_Calcul, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::MathPerso.Nombre, global::MathPerso.Resultat>(serviceImpl.Calcul));
    }

  }
}
#endregion
